name: Playwright Tests

on:
    push:
        branches: [master, main, develop]
    pull_request:
        branches: [master, main]
    schedule:
        - cron: '0 5 * * *' # Midnight EST (Florida)
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment'
                required: true
                default: 'dev'
                type: choice
                options: [dev, stage, prod]
            test_suite:
                description: 'Choose test suite to run'
                required: true
                default: '@smoke'
                type: choice
                options: ['@smoke', '@regression', '@ui', '@api', 'all']
            browser:
                description: 'Choose browser'
                required: true
                default: 'chromium'
                type: choice
                options: [chromium, firefox, webkit, all]

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    test:
        timeout-minutes: 30
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Install Playwright browsers
              run: npx playwright install --with-deps

            - name: Run Playwright tests
              run: |
                  TAG_VALUE="${{ github.event.inputs.test_suite || 'all' }}"
                  BROWSER_VALUE="${{ github.event.inputs.browser || 'all' }}"
                  COMMAND_OPTIONS_STRING=""
                  if [ "$TAG_VALUE" != "all" ]; then COMMAND_OPTIONS_STRING="$COMMAND_OPTIONS_STRING --grep $TAG_VALUE"; fi
                  if [ "$BROWSER_VALUE" != "all" ]; then COMMAND_OPTIONS_STRING="$COMMAND_OPTIONS_STRING --project=$BROWSER_VALUE"; fi
                  echo "Executing command: npx playwright test $COMMAND_OPTIONS_STRING"
                  npx playwright test $COMMAND_OPTIONS_STRING
              env:
                  ENV: ${{ github.event.inputs.environment || 'dev' }}
              continue-on-error: true

            - name: Generate Allure Report
              if: always()
              run: npm run allure:generate

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              if: always()
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: allure-report
                  publish_branch: gh-pages

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: allure-report
                  path: allure-report/
                  retention-days: 30
